# neops.core.provider.base.result.exception